package util;

/**
 * Challenges are generated to challenge a player to a certain minigame
 * (implicated by {@link #_accepted} == false) or to accept the challenge of
 * another player ({@link #_accepted} == true).<br>
 * They are automatically generated by the {@link ArenaFactory}.
 * 
 * @author Daniel
 *
 */
public class Challenge {
	private final int _challengerId;
	private final String _type;
	private final boolean _accepted;

	public boolean isAccepted() {
		return _accepted;
	}

	public int getChallengerId() {
		return _challengerId;
	}

	public String getType() {
		return _type;
	}

	/**
	 * Constructor
	 * 
	 * @param _challengerId
	 *            id of the challenging player
	 * @param _type
	 *            type (dragon,staghunt,skirmish)
	 * @param _accepted
	 *            whether it was an initial challenge (false) or accepting the
	 *            challenge (true)
	 */
	public Challenge(int challengerId, String type, boolean accepted) {
		_challengerId = challengerId;
		_type = type;
		_accepted = accepted;
	}
}