package util;

import java.util.ArrayList;
import java.util.List;

import tokenizer.ITokenizable;

/**
 * Challenges are generated to challenge a player to a certain minigame
 * (implicated by {@link #_accepted} == false) or to accept the challenge of
 * another player ({@link #_accepted} == true).<br>
 * They are automatically generated by the {@link ArenaFactory}.
 * 
 * @author Daniel
 *
 */
public class Challenge implements ITokenizable {
	private final int _challengerId;
	private final String _type;
	private final boolean _accepted;

	public boolean isAccepted() {
		return _accepted;
	}

	public int getChallengerId() {
		return _challengerId;
	}

	public String getType() {
		return _type;
	}

	/**
	 * Constructor
	 * 
	 * @param _challengerId
	 *            id of the challenging player
	 * @param _type
	 *            type (dragon,staghunt,skirmish)
	 * @param _accepted
	 *            whether it was an initial challenge (false) or accepting the
	 *            challenge (true)
	 */
	public Challenge(int challengerId, String type, boolean accepted) {
		_challengerId = challengerId;
		_type = type;
		_accepted = accepted;
	}

	/**
	 * begin:chal id:NR type:STRING accepted:BOOLEAN end:chal
	 */
	@Override
	public List<String> tokenize() {
		final ArrayList<String> tokens = new ArrayList<>();
		tokens.add(Const.PAR_BEGIN + Const.PAR_CHALLENGE);
		tokens.add(Const.PAR_ID + _challengerId);
		tokens.add(Const.PAR_TYPE + _type);
		tokens.add(Const.PAR_ACCEPTED + _accepted);
		tokens.add(Const.PAR_END + Const.PAR_CHALLENGE);
		return tokens;
	}
}